##
# =================
# SCHEMA - Measure
# =================
# Defines a Measure, generated by a Sensor.
##

cozydb = require 'cozydb'

module.exports = MeasureModel = cozydb.getModel 'Measure',
	time:		type : Date			# not Empty
	value: 		type : Number		# not Empty
	type: 		type : String		# not Empty
	sensorId:	type : String		# not Empty