###
# =================
# SCHEMA - Measure
# =================
# Defines a Measure, generated by a Sensor.
###

cozydb = require 'cozydb'

module.exports = class Measure extends cozydb.CozyModel
	@schema:
		time:		type : Date			# not Empty
		value: 		type : String		# not Empty
		type: 		type : String		# not Empty
		sensorId:	type : String		# not Empty
	
	@allBySensorAndTimeRange: (sensorId, timeMin, timeMax, callback) ->
		params =
			startkey: [sensorId + timeMin]
			endkey: [sensorId + timeMax]
		@request "bySensorAndTime", params, callback