// Generated by CoffeeScript 1.9.2

/*
* =================
* Fixtures - Driver File
* =================
* Driver Example for Tests.
*/

var areDevicesRemovable, isCustomIDValidExample, sensors;

sensors = [];

module.exports.isSensor = true;

areDevicesRemovable = true;

module.exports.setRemovableFlag = function(flag) {
  return areDevicesRemovable = flag;
};

module.exports.getSensor = function(customId) {
  return sensors[customId];
};

module.exports.init = function(callback) {
  return callback(null);
};

module.exports.add = function(customId, id, callback) {
  if (sensors[customId]) {
    return callback('Custom ID already used.');
  } else {
    if (isCustomIDValidExample(customId)) {
      sensors[customId] = id;
      return callback(null);
    } else {
      return callback("Invalid CustomId");
    }
  }
};

module.exports.remove = function(customId, id, callback) {
  if (areDevicesRemovable) {
    delete sensors[customId];
    return callback(null);
  } else {
    return callback("Device not removable");
  }
};

module.exports.update = function(oldCustomId, newCustomId, callback) {
  if (sensors[newCustomId]) {
    return callback('Custom ID already used.');
  } else {
    if (isCustomIDValidExample(newCustomId)) {
      sensors[newCustomId] = sensors[oldCustomId];
      sensors[oldCustomId] = null;
      return callback(null);
    } else {
      return callback("Invalid CustomId");
    }
  }
};

isCustomIDValidExample = function(customId) {
  return !isNaN(parseInt(customId.split("ID")[1]));
};

